Matrix operations 

In [1]:
import numpy as np    # it is an unofficial standard to use np for numpy
import time

In [2]:
# Creating 2D arrays with different shapes using NumPy
# Each example demonstrates how shape parameters affect array dimensions

# Example 1: Create a 1x5 array (1 row, 5 columns) filled with zeros
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

# Example 2: Create a 2x1 array (2 rows, 1 column) filled with zeros
a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

# Example 3: Create a 1x1 array (single element) with random value between 0 and 1
a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

# Example 4: Create a 3x4 array (3 rows, 4 columns) filled with zeros
a = np.zeros((3, 4))
print(f"a shape = {a.shape}, a = {a}")

# Example 5: Create a 2x3 array (2 rows, 3 columns) with random values
a = np.random.random_sample((2, 3))
print(f"a shape = {a.shape}, a = {a}")

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.42004713]]
a shape = (3, 4), a = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
a shape = (2, 3), a = [[0.99895059 0.11048141 0.3499671 ]
 [0.5716996  0.93916629 0.2282278 ]]


In [3]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


In [4]:
# Matrix indexing operations and element access demonstrations
# Creating a 3x2 matrix using reshape for better visualization
matrix = np.arange(12).reshape(-1, 3)   # reshape creates a 4x3 matrix from 12 elements
print(f"matrix.shape: {matrix.shape}, \nmatrix = \n{matrix}")

# Accessing individual elements using row, column indexing
print(f"\nmatrix[1,2].shape: {matrix[1, 2].shape}, matrix[1,2] = {matrix[1, 2]}, type(matrix[1,2]) = {type(matrix[1, 2])} - Single element access returns a scalar")

# Accessing entire rows using single index
print(f"matrix[2].shape: {matrix[2].shape}, matrix[2] = {matrix[2]}, type(matrix[2]) = {type(matrix[2])} - Row access returns a 1D array")

# Additional practice 1: Column access using slicing
print(f"\nmatrix[:, 1].shape: {matrix[:, 1].shape}, matrix[:, 1] = {matrix[:, 1]}, type(matrix[:, 1]) = {type(matrix[:, 1])} - Column access using slicing")

# Additional practice 2: Submatrix extraction using slicing
print(f"matrix[1:3, 0:2].shape: {matrix[1:3, 0:2].shape}, matrix[1:3, 0:2] = \n{matrix[1:3, 0:2]}, type(matrix[1:3, 0:2]) = {type(matrix[1:3, 0:2])} - Submatrix extraction")

matrix.shape: (4, 3), 
matrix = 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

matrix[1,2].shape: (), matrix[1,2] = 5, type(matrix[1,2]) = <class 'numpy.int64'> - Single element access returns a scalar
matrix[2].shape: (3,), matrix[2] = [6 7 8], type(matrix[2]) = <class 'numpy.ndarray'> - Row access returns a 1D array

matrix[:, 1].shape: (4,), matrix[:, 1] = [ 1  4  7 10], type(matrix[:, 1]) = <class 'numpy.ndarray'> - Column access using slicing
matrix[1:3, 0:2].shape: (2, 2), matrix[1:3, 0:2] = 
[[3 4]
 [6 7]], type(matrix[1:3, 0:2]) = <class 'numpy.ndarray'> - Submatrix extraction


In [5]:
# 2-D array slicing operations with different sample data
a = np.arange(30).reshape(-1, 15)  # Create 2x15 array with numbers 0-29
print(f"a = \n{a}")

# Extract 6 consecutive elements from the first row (start:stop:step)
print("a[0, 3:9:1] = ", a[0, 3:9:1], ",  a[0, 3:9:1].shape =", a[0, 3:9:1].shape, "a 1-D array")

# Extract 6 consecutive elements from all rows (start:stop:step)
print("a[:, 3:9:1] = \n", a[:, 3:9:1], ",  a[:, 3:9:1].shape =", a[:, 3:9:1].shape, "a 2-D array")

# Access all elements in the entire array
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# Access all elements in the second row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# Same operation using simplified syntax
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")

# Additional practice: Extract every other element from the first row
print("a[0, ::2] = ", a[0, ::2], ",  a[0, ::2].shape =", a[0, ::2].shape, "a 1-D array with step=2")

# Additional practice: Extract elements from both rows using different ranges
print("a[:, 5:12:2] = \n", a[:, 5:12:2], ",  a[:, 5:12:2].shape =", a[:, 5:12:2].shape, "a 2-D array with step=2")

a = 
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
a[0, 3:9:1] =  [3 4 5 6 7 8] ,  a[0, 3:9:1].shape = (6,) a 1-D array
a[:, 3:9:1] = 
 [[ 3  4  5  6  7  8]
 [18 19 20 21 22 23]] ,  a[:, 3:9:1].shape = (2, 6) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]] ,  a[:,:].shape = (2, 15)
a[1,:] =  [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29] ,  a[1,:].shape = (15,) a 1-D array
a[1]   =  [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29] ,  a[1].shape   = (15,) a 1-D array
a[0, ::2] =  [ 0  2  4  6  8 10 12 14] ,  a[0, ::2].shape = (8,) a 1-D array with step=2
a[:, 5:12:2] = 
 [[ 5  7  9 11]
 [20 22 24 26]] ,  a[:, 5:12:2].shape = (2, 4) a 2-D array with step=2
