An introduction to the scientific computing concepts used in this course, with a focus on the NumPy package and its applications in Python.

In [1]:
import numpy as np    # it is an unofficial standard to use np for numpy
import time

[NumPy Documentation](https://numpy.org/)
 — includes a basic introduction

[NumPy Broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html)
 — a more advanced feature topic

In NumPy, most data creation functions take the shape of the array as their first parameter. For a one-dimensional array, this is simply a single integer. For higher-dimensional arrays, the shape is specified as a tuple (n, m, ...). The examples below demonstrate how to create vectors using these functions.

In [5]:
# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}") #column vector
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}") #row vector
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}") #random vector

# NumPy routines which allocate memory and fill arrays with value
print("NumPy routines which allocate memory and fill arrays with value")
a = np.zeros((4,4));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}") #row vector
a = np.random.random_sample((4,4)); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}") #random vector


np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.98801827 0.86609011 0.102767   0.54158255], a shape = (4,), a data type = float64
NumPy routines which allocate memory and fill arrays with value
np.zeros(4,) :  a = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], a shape = (4, 4), a data type = float64
np.random.random_sample(4): a = [[0.81935641 0.27492705 0.01412064 0.33498257]
 [0.67179178 0.38092773 0.3487361  0.92849197]
 [0.13156726 0.47618986 0.37897459 0.51351715]
 [0.87977977 0.27779469 0.99613133 0.71763221]], a shape = (4, 4), a data type = float64


In [8]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.);              print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

# difference between (4. ) and (4,) is that (4. ) is a row vector and 
# (4,) is a column vector

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.12636773 0.66553577 0.63246666 0.84687347], a shape = (4,), a data type = float64


Manually

In [9]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


You can access elements of a vector using indexing and slicing. NumPy offers a wide range of powerful options for both, but we’ll focus on the basics needed for this course. For more details, see the documentation on Slicing and Indexing.

Indexing refers to selecting a single element of an array by its position.

Slicing refers to retrieving a subset of elements from an array using index ranges.

Note that NumPy uses zero-based indexing. This means the 3rd element of a vector a is accessed with a[2].

In [13]:
#vector indexing operations on 1-D vectors
a = np.arange(10)
print(a)

#access an element
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")
# what is the a[2.shape? it is a scalar that means it is a single value and showing the shape of a[2] is showing the shape of a single value
# by shape we mean the number of dimensions and the size of each dimension
print(f"a[2]  = {a[2]}, Accessing an element returns a scalar")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

#indexs must be within the range of the vector or they will produce and error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


Slicing generates an array of indices defined by three parameters: start:stop:step. You can also provide just a subset of these values. The concept is best illustrated through examples:

In [15]:
#access 4 consecutive elements (start:stop:step)
c = a[2:6:1];     print("a[2:6:1] = ", c)
# 2:6:1 means start from index 2 and end at index 6 and step is 1

# access 2 elements separated by two 
c = a[2:5:2];     print("a[2:5:2] = ", c)
# 2:5:2 means start from index 2 and end at index 5 and step is 2


# access all elements index 2 and above
c = a[2:];        print("a[2:]    = ", c)
# 2: means start from index 2 and end at the last index


# access all elements below index 4
c = a[:4];        print("a[:4]    = ", c)
# 4 means end at index 4


# access all elements
c = a[:];         print("a[:]     = ", c)
# : means start from the first index and end at the last index

# access all elements in reverse order
c = a[::-1];     print("a[::-1]  = ", c)
# -1 means step is -1 for reverse order

a[2:6:1] =  [2 3 4 5]
a[2:5:2] =  [2 4]
a[2:]    =  [2 3 4 5 6 7 8 9]
a[:4]    =  [0 1 2 3]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]
a[::-1]  =  [9 8 7 6 5 4 3 2 1 0]


I can provide a few more alternatives with slightly different tones if you want. Do you want me to?

In [17]:
# Creating a NumPy array with different numbers
a = np.array([7, 3, 9, 2, 5])  # Array with 5 elements
print(f"a             : {a}")

# Negate elements of a - applies negative sign to each element
b = -a 
print(f"b = -a        : {b}")

# Sum all elements of a, returns a scalar (single number)
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")

# Calculate the mean (average) of all elements in a
b = np.mean(a)
print(f"b = np.mean(a): {b}")

# Square each element of a (element-wise operation)
b = a**2
print(f"b = a**2      : {b}")

a             : [7 3 9 2 5]
b = -a        : [-7 -3 -9 -2 -5]
b = np.sum(a) : 26
b = np.mean(a): 5.2
b = a**2      : [49  9 81  4 25]


Many of NumPy’s arithmetic, logical, and comparison operations can also be applied to vectors. These operators perform calculations element by element. For instance
$$ c_i = a_i + b_i $$

In [23]:
# Creating two NumPy arrays with different values
a = np.array([1, 2, 3, 4])   # First array with positive values
b = np.array([-1, -2, 3, 4]) # Second array with mixed positive and negative values

# Binary operators work element-wise - they perform operations between corresponding elements
print(f"Binary operators work element wise: {a + b}")

# Let's demonstrate other binary operations for better understanding
print(f"Element-wise addition (a + b): {a + b}")
print(f"Element-wise subtraction (a - b): {a - b}")
print(f"Element-wise multiplication (a * b): {a * b}")
print(f"Element-wise division (a / b): {a / b}")
print(f"Element-wise power (a ** 2): {a ** 2}")


Binary operators work element wise: [0 0 6 8]
Element-wise addition (a + b): [0 0 6 8]
Element-wise subtraction (a - b): [2 4 0 0]
Element-wise multiplication (a * b): [-1 -4  9 16]
Element-wise division (a / b): [-1. -1.  1.  1.]
Element-wise power (a ** 2): [ 1  4  9 16]


In [28]:
# Demonstrating vector operations with different numbers
print("=== VECTOR OPERATIONS ===")

# Create vectors with different numbers
vector_a = np.array([10, 20, 30, 40])
vector_b = np.array([5, 15, 25, 35])

print(f"Vector A: {vector_a}, shape: {vector_a.shape}")
print(f"Vector B: {vector_b}, shape: {vector_b.shape}")

# Successful operations
result_add = vector_a + vector_b
print(f"Addition: {result_add}")

# Broadcasting example
scalar = 7
broadcast_result = vector_a + scalar
print(f"Broadcasting: {broadcast_result}")


=== VECTOR OPERATIONS ===
Vector A: [10 20 30 40], shape: (4,)
Vector B: [ 5 15 25 35], shape: (4,)
Addition: [15 35 55 75]
Broadcasting: [17 27 37 47]


In [26]:

print("\n=== INCOMPATIBLE OPERATIONS ===")

# Mismatched vector operation that will fail
main_vector = np.array([1, 2, 3, 4, 5])  # 5 elements
mismatched_vector = np.array([10, 20])   # 2 elements

print(f"Main vector: {main_vector}, shape: {main_vector.shape}")
print(f"Mismatched vector: {mismatched_vector}, shape: {mismatched_vector.shape}")

try:
    failed_result = main_vector + mismatched_vector
    print(f"Unexpected success: {failed_result}")
except Exception as e:
    print("The error message you'll see is:")
    print(f"Error: {e}")
    print("This happens because arrays have incompatible shapes")


=== INCOMPATIBLE OPERATIONS ===
Main vector: [1 2 3 4 5], shape: (5,)
Mismatched vector: [10 20], shape: (2,)
The error message you'll see is:
Error: operands could not be broadcast together with shapes (5,) (2,) 
This happens because arrays have incompatible shapes


Vectors can be scaled using scalar values, which are simply numbers. When a vector is multiplied by a scalar, each of its elements is multiplied by that number.

In [31]:
# Create a sample vector with new values
a = np.array([7, 12, 15, 8])

# Scalar multiplication: multiply each element by a constant
b = 3 * a 
print(f"b = 3 * a : {b}")

# Vector addition: add corresponding elements of two vectors
c = np.array([2, 5, 3, 1])
d = a + c
print(f"d = a + c : {d}")

# Element-wise multiplication: multiply corresponding elements
e = a * c
print(f"e = a * c : {e}")

b = 3 * a : [21 36 45 24]
d = a + c : [ 9 17 18  9]
e = a * c : [14 60 45  8]


The dot product is a fundamental concept in Linear Algebra and a core operation in NumPy. It is used extensively throughout this course, so it’s important to understand it thoroughly. The dot product is illustrated below.

example:
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
Assume both `a` and `b` are the same shape.

In [32]:
def my_dot(a, b): 
    """
    Compute the dot product of two vectors using NumPy dot function
    
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): dot product of vectors a and b
    """
    x = np.dot(a, b)
    return x

In [33]:

# Example usage
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

result = my_dot(a, b)
print(f"Dot product of {a} and {b} = {result}")

# Verification: manual calculation
manual_result = 1*5 + 2*6 + 3*7 + 4*8
print(f"Manual calculation: {manual_result}")

Dot product of [1 2 3 4] and [5 6 7 8] = 70
Manual calculation: 70


Without numpy:

In [36]:
def my_dot_loop(a, b): 
    """
    Compute the dot product of two vectors using a manual loop
 
    """
    x = 0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x


Speed Test:

In [ ]:
def speed_test():
    """
    Test the speed of loop vs NumPy dot implementations
    """
    # Test with different vector sizes
    # to print the time it took for each method to run
    sizes = [100, 1000, 10000, 100000]
    
    for size in sizes:
        print(f"\nTesting with vectors of size {size}:")
        
        # Create random vectors
        a = np.random.rand(size)
        b = np.random.rand(size)
        
        # Test loop implementation
        start_time = time.time()
        result_loop = my_dot_loop(a, b)
        loop_time = time.time() - start_time
        
        # Test NumPy dot implementation
        start_time = time.time()
        result_numpy = my_dot(a, b)
        numpy_time = time.time() - start_time
        
        # Verify both methods give the same result
        print(f"Results match: {np.allclose(result_loop, result_numpy)}") 
        # np.allclose is a function that checks if two arrays are equal
        # I am doing this to make sure that the two methods give the same result
        # then I am printing the time it took for each method to run

        print(f"Loop method:   {loop_time:.6f} seconds")
        print(f"NumPy dot:     {numpy_time:.6f} seconds")
        print(f"Speedup:       {loop_time/numpy_time:.2f}x")

# Run the speed test
speed_test()


Testing with vectors of size 100:
Results match: True
Loop method:   0.000028 seconds
NumPy dot:     0.000039 seconds
Speedup:       0.72x

Testing with vectors of size 1000:
Results match: True
Loop method:   0.000158 seconds
NumPy dot:     0.000004 seconds
Speedup:       44.13x

Testing with vectors of size 10000:
Results match: True
Loop method:   0.001542 seconds
NumPy dot:     0.000008 seconds
Speedup:       196.03x

Testing with vectors of size 100000:
Results match: True
Loop method:   0.016599 seconds
NumPy dot:     0.001039 seconds
Speedup:       15.98x
